apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-secret: ocir-secret
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apache
  name: apache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apache
    spec:
      containers:
      - image: iad.ocir.io/restoncloudhub/tomhuang/apache:latest
        name: apache
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/
          name: apache-claim0
        resources:
          requests:
            memory: "64Mi"
            cpu: "75m"
      imagePullSecrets:
      - name: ocir-secret
      restartPolicy: Always
      volumes:
      - name: apache-claim0
        persistentVolumeClaim:
          claimName: apache-claim0

status: {}
